#!/bin/bash

#BSUB -nnodes 16
# #BSUB -q pdebug
# #BSUB -G guests
#BSUB -q pbatch
#BSUB -G callat_g
#BSUB -W 30
#BSUB -o stag_profile.64x64x64x128.n16.2x2x2x8.gdr.%J
## Uncomment to make this interactive
# #BSUB -Is
##
#BSUB -core_isolation 2
####BSUB -x

module load gcc/7.3.1
module load cmake/3.12.1


export QUDA_RESOURCE_PATH=$(pwd)/tunecache_64x64x64x128_2x2x2x8_gdr/
export QUDA_ENABLE_GDR=1 

echo "Changed dir"


APP="/nfs/tmp2/lsd/weinberg/new_bin/scidac/quda/build/tests/staggered_invert_test"
ARG="--rank-order col --dim 32 32 32 16 --gridsize 2 2 2 8 --load-gauge l64t128m00125b480_config.17100.lime --compute-fat-long true --dslash-type staggered --test 1 --niter 1000000 --tol 1e-10 --prec double --prec-sloppy half --mass 0.00125"
PROG="$APP $ARG"
#APRUNVAR="jsrun -p16 -r4 --bind=none ./sierra_jsrun.reorder.sh $PROG"
APRUNVAR="jsrun -p64 -g1 -M \"-gpu\" --bind=none ./sierra_jsrun.reorder.sh $PROG"

echo "About to run job"
echo "${APRUNVAR}"

$APRUNVAR 

echo "Job ran."

