#!/bin/bash

#BSUB -nnodes 4
# #BSUB -q pdebug
# #BSUB -G guests
#BSUB -q pbatch
#BSUB -G callat_g
#BSUB -W 30
#BSUB -o stag_profile.48x48x48x96.n2.1x2x2x4.gdr.%J
## Uncomment to make this interactive
# #BSUB -Is
##
#BSUB -core_isolation 2
####BSUB -x

module load gcc/7.3.1
module load cmake/3.12.1

export QUDA_RESOURCE_PATH=$(pwd)/tunecache_48x48x48x96_1x2x2x4_gdr/
export QUDA_ENABLE_GDR=1 

APP="/nfs/tmp2/lsd/weinberg/new_bin/scidac/quda/build/tests/staggered_invert_test"
ARG="--rank-order col --dim 48 24 24 24 --gridsize 1 2 2 4 --load-gauge l48t96m00222b480_config.9990.lime --compute-fat-long true --dslash-type staggered --test 1 --niter 1000000 --tol 1e-10 --prec double --prec-sloppy half --mass 0.00222"
PROG="$APP $ARG"
#APRUNVAR="jsrun -p16 -r4 --bind=none ./sierra_jsrun.reorder.sh $PROG"
APRUNVAR="jsrun -p16 -g1 -M \"-gpu\" --bind=none ./sierra_jsrun.reorder.sh $PROG"

echo "About to run job"
echo "${APRUNVAR}"

$APRUNVAR 

echo "Job ran."

